/*GRUPO 3, CADENA DE TIENDAS*/
/*PEREZ REYES ALISSON*/

/* CONSULTA DE TODAS LAS TIENDAS DE DIRECCIÓN QUE EMPIEZAN CON ‘C’ Y TERMINAN EN CÓDIGO POSTAL ‘0867’*/

SELECT * FROM TIENDA WHERE TIENDA_DIRECCION LIKE 'C%' AND TIENDA_CODIGOPOSTAL LIKE'%0867'

/* CONSULTA DE TODAS LAS TIENDAS DE DIRECCIÓN QUE EMPIEZAN CON ‘C’ Y TERMINAN EN CÓDIGO POSTAL ‘0867’*/

SELECT * FROM EMPLEADO WHERE EXTRACT(YEAR FROM EMPLEADO_FECHA_INCORPORACION) = 2020

/* CONSULTA DE TODOS LOS GERENTES DE TIENDA QUE NOMBRES QUE EMPIEZAN CON ‘ERAZO’*/

SELECT * FROM GERENTE WHERE GERENTE_NOMBRE LIKE'ERAZO%'


/* CONSULTA DE TODOS LOS ARTÍCULOS DE PRECIO > 100 Y STOCK<50*/

SELECT * FROM ARTICULO WHERE  ARTICULO_PRECIO > 100 AND ARTICULO_STOCK < 50

/* CONSULTA DEL STOCK Y PRECIO DEL ARTICULO CON CÓDIGO ‘A12’*/

SELECT ARTICULO_STOCK, ARTICULO_PRECIO FROM ARTICULO WHERE ARTICULO_COD='A12'

/* CONSULTA DE TODOS LOS DATOS DE LA FACTURA ‘F1212’ ENTRE LOS AÑOS 2005 A 2010*/

SELECT * FROM 
TIENDA INNER JOIN GERENTE ON TIENDA.TIENDA_COD= GERENTE.TIENDA_COD
INNER JOIN EMPLEADO ON TIENDA.TIENDA_COD = EMPLEADO.TIENDA_COD
INNER JOIN ARTICULO ON TIENDA.TIENDA_COD = ARTICULO.TIENDA_COD
INNER JOIN FACTURA ON TIENDA.TIENDA_COD = FACTURA.TIENDA_COD
INNER JOIN DETALLE_FACTURA ON FACTURA.FACTURA_CODE= DETALLE_FACTURA.FACTURA_CODE
INNER JOIN CLIENTE ON CLIENTE.CLIENTE_DNI = FACTURA.CLIENTE_DNI
WHERE FACTURA.FACTURA_CODE='F1212'


/* CONSULTA DE TODAS LAS FACTURAS DEL CLIENTE CON CEDULA ‘1314564560’*/

SELECT * FROM 
TIENDA 
INNER JOIN ARTICULO ON TIENDA.TIENDA_COD = ARTICULO.TIENDA_COD
INNER JOIN FACTURA ON TIENDA.TIENDA_COD = FACTURA.TIENDA_COD
INNER JOIN DETALLE_FACTURA ON FACTURA.FACTURA_CODE= DETALLE_FACTURA.FACTURA_CODE
INNER JOIN CLIENTE ON CLIENTE.CLIENTE_DNI = FACTURA.CLIENTE_DNI
WHERE CLIENTE.CLIENTE_DNI='1314564560'


/* CONSULTA DE TODAS LOS MININOS DE STOCK DE LOS DATOS DE LOS ARTÍCULOS ORDENADO DESCENDENTE*/
SELECT * FROM ARTICULO
ORDER BY ARTICULO_STOCK DESC

/* CONSULTA DE LA SUMA DE TOTAL DE LAS FACTURAS ENTRE LOS AÑOS 2000 A 2010*/

SELECT SUM(DETALLEFACTURA_TOTAL) AS TOTAL FROM FACTURA 
INNER JOIN DETALLE_FACTURA  ON FACTURA.FACTURA_CODE = DETALLE_FACTURA.FACTURA_CODE 
WHERE EXTRACT(YEAR FROM FACTURA_FECHA) > 1999 AND EXTRACT(YEAR FROM FACTURA_FECHA) < 2011

/* CONSULTA DE EN QUE AÑO 2005, 2007, 2008 SE FACTURO MÁS*/

SELECT FACTURA.FACTURA_FECHA, DETALLEFACTURA_TOTAL FROM FACTURA 
INNER JOIN DETALLE_FACTURA  ON FACTURA.FACTURA_CODE = DETALLE_FACTURA.FACTURA_CODE 
WHERE EXTRACT(YEAR FROM FACTURA_FECHA) >= 2005 AND EXTRACT(YEAR FROM FACTURA_FECHA) <= 2008 
GROUP BY FACTURA.FACTURA_FECHA,DETALLEFACTURA_TOTAL















